# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='post-images'),
        ),
    ]
