# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20160601_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='fecha',
            new_name='fechal',
        ),
    ]
