# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20160603_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fechal',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
